import type { Metadata } from "next";
import "./globals.css";
import { roboto, montserrat } from "@/components/ui/font";
import Navbar from "@/components/root-layout/navbar/page";
import Footer from "@/components/root-layout/footer/page";
import AuthProvider from "@/app/context/AuthProvider";


export const metadata: Metadata = {
  title: "CSC",
  description: "Generated by create next app",
};


export default function RootLayout({  
  children,  
}: Readonly<{  
  children: React.ReactNode;  
}>) {  
  return (  
    <html lang="en">  
      <AuthProvider>  
          <body className={`${montserrat.className} antialiased`}>  
            <div>  
              <Navbar />  
              <div>{children}</div>   
              <Footer />  
            </div>  
          </body>  

      </AuthProvider>  
    </html>  
  );  
}  
