import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto  } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/app/context/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "CSC",
  description: "Generated by create next app",
};


export default function RootLayout({  
  children,  
}: Readonly<{  
  children: React.ReactNode;  
}>) {  
  return (  
    <html lang="en">  
      <AuthProvider>  
          <body className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} antialiased`}>  
            <div>  
              <Header />  
              <div>{children}</div>   
              <Footer />  
            </div>  
          </body>  

      </AuthProvider>  
    </html>  
  );  
}  
