import { AlertCircle, ArrowRight, Check, ChevronLeft, ChevronRight, Command, CreditCard, File, FileText, HelpCircle, Image, Laptop, Loader2, Moon, MoreVertical, Pizza, Plus, Settings, SunMedium, Trash, Twitter, User, X, Upload, School, BookOpen, GraduationCap, Calendar, Mail, Phone, MapPin, Briefcase, CheckCircle2 } from 'lucide-react'

export type IconProps = React.HTMLAttributes<SVGElement>

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  creditCard: CreditCard,
  twitter: Twitter,
  check: Check,
  warning: AlertCircle,
  file: File,
  fileText: FileText,
  plus: Plus,
  image: Image,
  moreVertical: MoreVertical,
  upload: Upload,
  school: School,
  bookOpen: BookOpen,
  graduationCap: GraduationCap,
  calendar: Calendar,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  briefcase: Briefcase,
  checkCircle: CheckCircle2,
}
